apiVersion: v1
kind: Service
metadata:
  name: camp-dns-service
spec:
  type: ClusterIP
  selector:
    app: unbound
  ports:
    - name: dns-udp
      targetPort: 53
      port: 53
      protocol: UDP
    - name: dns-tcp
      targetPort: 53
      port: 53
      protocol: TCP
  externalIPs:
    - 10.108.231.189
