unbound:
  image:
    repository: wide-camp-1909/camp-dns
    tag: latest
    pullPolicy: IfNotPresent
  replicaCountMin: 4
  replicaCountMax: 16
  averageUtilization: 80
  listen:
    - 203.178.158.1
    - 203.178.158.2
  allow:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 203.178.156.0/22

rsyslogd:
  server: 203.178.156.10
